{% set name = "qiskit-terra" %}
{% set version = "0.46.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 48e0e193e322fe9ee7201a8f8a7b8e3dd463c4804e64c36a733d7ad34acdddb7

build:
  number: 1
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses
  host:
    - pip
    - python
    - setuptools
    - setuptools-rust
    - wheel
  run:
    - typing-extensions  # [py<311]
    - rustworkx >=0.13.0
    - python
    - numpy >=1.17,<3
    - ply >=3.10
    - psutil >=5
    - scipy >=1.5
    - sympy >=1.3
    - dill >=0.3
    - python-dateutil >=2.8.0
    - stevedore >=3.0.0
    - python-symengine >=0.11
  run_constrained:
    - matplotlib >=3.3
    - matplotlib-base >=3.3
    - ipywidgets >=7.3.0
    - pillow >=4.2.1
    - pylatexenc >=1.4
    - seaborn >=0.9.0
    - pygments >=2.4
    - z3-solver >=4.7

test:
  imports:
    - qiskit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.ibm.com/quantum/qiskit
  summary: SDK for working with quantum computers at the level of extended quantum circuits, operators, and primitives.
  doc_url: https://docs.quantum.ibm.com
  dev_url: https://github.com/Qiskit/qiskit
  license: Apache-2.0
  license_file:
    - THIRDPARTY.yml
    - LICENSE.txt

extra:
  recipe-maintainers:
    - BastianZim
    - wshanks
