{% set name = "qiskit-terra" %}
{% set version = "0.45.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qiskit-terra-{{ version }}.tar.gz
  sha256: fe58d2fb123395853b426e7bd3747cdba4152573c7c3be1f19b5cd20bef92664

build:
  number: 0
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - pip
    - python
    - setuptools
    - setuptools-rust
    - wheel
  run:
    - typing-extensions
    - importlib-metadata <5.0  # [py<39]
    - rustworkx >=0.13.0
    - python
    - numpy >=1.17,<2
    - ply >=3.10
    - psutil >=5
    - scipy >=1.5
    - sympy >=1.3
    - dill >=0.3
    - python-dateutil >=2.8.0
    - stevedore >=3.0.0
    - python-symengine >=0.9,<0.10
  run_constrained:
    - matplotlib >=3.3
    - matplotlib-base >=3.3
    - ipywidgets >=7.3.0
    - pillow >=4.2.1
    - pylatexenc >=1.4
    - seaborn >=0.9.0
    - pygments >=2.4
    - z3-solver >=4.7
    - qiskit-toqm >=0.1.0
    - qiskit-qasm3-import >=0.1.0

test:
  imports:
    - qiskit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://qiskit.org/
  summary: Software for developing quantum computing programs
  doc_url: https://qiskit.org/documentation/index.html
  dev_url: https://github.com/Qiskit/qiskit
  license: Apache-2.0
  license_file:
    - THIRDPARTY.yml
    - LICENSE.txt

extra:
  recipe-maintainers:
    - BastianZim
    - wshanks
