{% set name = "qiskit-terra" %}
{% set version = "0.25.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qiskit-terra-{{ version }}.tar.gz
    sha256: 1ea5981800377af5cc8beefd5ca62e18196b918058de8382a129abc921fa3c8b
    folder: terra
  - url: https://pypi.io/packages/source/q/qiskit/qiskit-0.44.1.tar.gz
    sha256: 353c1aa2624c4044bd7013bd1e996a736c60934ebe323119c1f5b07527c6b05f
    folder: qiskit

build:
  number: 1
  skip: true  # [win]

outputs:
  - name: qiskit-terra
    build:
      script:
        # cargo-bundle-licenses must be run in directory with Cargo.toml
        - cd terra && cargo-bundle-licenses --format yaml --output ../THIRDPARTY.yml && cd ..
        - {{ PYTHON }} -m pip install ./terra -vv --no-deps --no-index --no-build-isolation --ignore-installed --cache-dir pip_cache
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - {{ compiler('rust') }}
        - cargo-bundle-licenses
      host:
        - tomli  # Temporary workaround to missing setuptools-rust dependency
        - pip
        - python
        - setuptools
        - setuptools-rust
        - wheel
      run:
        - typing-extensions
        - importlib-metadata <5.0  # [py<39]
        - rustworkx >=0.13.0
        - python
        - numpy >=1.17
        - ply >=3.10
        - psutil >=5
        - scipy >=1.5
        - sympy >=1.3
        - dill >=0.3
        - python-dateutil >=2.8.0
        - stevedore >=3.0.0
        - python-symengine >=0.9,<0.10
      run_constrained:
        - matplotlib >=3.3
        - matplotlib-base >=3.3
        - ipywidgets >=7.3.0
        - pillow >=4.2.1
        - pylatexenc >=1.4
        - seaborn >=0.9.0
        - pygments >=2.4
        - z3-solver >=4.7
        - qiskit-toqm >=0.1.0
        - qiskit-qasm3-import >=0.1.0

    test:
      imports:
        - qiskit
      commands:
        - pip check
      requires:
        - pip

    about:
      home: https://github.com/Qiskit/qiskit
      summary: Software for developing quantum computing programs
      license: Apache-2.0
      license_file:
        - THIRDPARTY.yml
        - terra/LICENSE.txt

  - name: qiskit
    version: 0.44.1
    build:
      number: 0
      script: {{ PYTHON }} -m pip install ./qiskit -vv --no-deps --no-index --no-build-isolation --ignore-installed --cache-dir pip_cache
    requirements:
      host:
        - pip
        - python
      run:
        - {{ pin_subpackage('qiskit-terra', max_pin="x.x.x") }}
    test:
      imports:
        - qiskit
      commands:
        - pip check
      requires:
        - pip

    about:
      home: https://github.com/Qiskit/qiskit
      summary: Software for developing quantum computing programs
      license: Apache-2.0
      license_file:
        - qiskit/LICENSE.txt

about:
  home: https://github.com/Qiskit/qiskit
  summary: Software for developing quantum computing programs
  license: Apache-2.0
  license_file:
    - THIRDPARTY.yml
    - terra/LICENSE.txt


extra:
  recipe-maintainers:
    - BastianZim
    - wshanks
