{% set name = "qiskit-terra" %}
{% set version = "0.46.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qiskit-terra-{{ version }}.tar.gz
  sha256: 49ba03cfe49b38b81a9e3144637bf036a82d38f97333f3871dee7b72a5f1f094

build:
  number: 0
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv
  ignore_run_exports_from:  # [python_impl != "pypy"]
    - python  # [python_impl != "pypy"]
  string: pyabi3_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [python_impl != "pypy"]
  skip: true  # [py != 38 and python_impl != "pypy"]

requirements:
  build:
    - python =3.8                            # [build_platform != target_platform and python_impl != "pypy"]
    - python                                 # [build_platform != target_platform and python_impl == "pypy"]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - pip
    - python =3.8  # [python_impl != "pypy"]
    - python
    - setuptools
    - setuptools-rust
    - wheel
  run:
    - typing-extensions
    - rustworkx >=0.13.0
    - python  # [python_impl == "pypy"]
    - python >=3.8
    - numpy >=1.17,<2
    - ply >=3.10
    - psutil >=5
    - scipy >=1.5
    - sympy >=1.3
    - dill >=0.3
    - python-dateutil >=2.8.0
    - stevedore >=3.0.0
    - python-symengine >=0.11
  run_constrained:
    - matplotlib >=3.3
    - matplotlib-base >=3.3
    - ipywidgets >=7.3.0
    - pillow >=4.2.1
    - pylatexenc >=1.4
    - seaborn >=0.9.0
    - pygments >=2.4
    - z3-solver >=4.7

test:
  # Fails for 0.46 without qiskit package
  # imports:
  #   - qiskit
  commands:
    - pip check
  requires:
    - abi3audit
    - pip

about:
  home: https://qiskit.org/
  summary: Software for developing quantum computing programs
  doc_url: https://qiskit.org/documentation/index.html
  dev_url: https://github.com/Qiskit/qiskit
  license: Apache-2.0
  license_file:
    - THIRDPARTY.yml
    - LICENSE.txt

extra:
  recipe-maintainers:
    - BastianZim
    - wshanks
