{% set name = "qiskit-terra" %}
{% set version = "0.21.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qiskit-terra-{{ version }}.tar.gz
  sha256: af0758eb4b1d6325e7e55bedb4ce9d7a538035ee7fb1a75cda6d2739b4d6f73f

build:
  number: 0
  skip: true  # [win]
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - pip
    - python
    - setuptools
    - setuptools-rust
    - wheel
  run:
    - dill >=0.3
    - numpy >=1.17
    - ply >=3.10
    - psutil >=5
    - python
    - python-dateutil >=2.8.0
    - retworkx >=0.11.0
    - scipy >=1.5
    - shared-memory38  # [py==37]
    - stevedore >=3.0.0
    - python-symengine >=0.9
    - sympy >=1.3
    - tweedledum >=1.1,<2.0
    - typing-extensions  # [py==37]
  run_constrained:
    - matplotlib >=3.3
    - matplotlib-base >=3.3
    - ipywidgets >=7.3.0
    - pillow >=4.2.1
    - pylatexenc >=1.4
    - seaborn >=0.9.0
    - pygments >=2.4
    - z3-solver >=4.7

test:
  imports:
    - qiskit
    - qiskit.algorithms
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Qiskit/qiskit-terra
  summary: Software for developing quantum computing programs
  license: Apache-2.0
  license_file:
    - THIRDPARTY.yml
    - LICENSE.txt

extra:
  recipe-maintainers:
    - BastianZim
